image: Ubuntu

stack: jdk 11

branches:
  only:
    - master
    - JSON-Schema

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-mbank.jar &
  
build_script:
  - ./gradlew test --info
